# Generated by Django 3.2.13 on 2022-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='accounts/avatar/null.png', upload_to='chat/avatar/'),
        ),
    ]
